package ci

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WorkflowOptions configures the generated GitHub Actions workflow.
type WorkflowOptions struct {
	// RunnerLabels are the runs-on labels for the job.
	RunnerLabels []string
	// EnablePush uncomments the push trigger.
	EnablePush bool
	// EnablePR uncomments the pull_request trigger.
	EnablePR bool
}

// GenerateWorkflow returns the GitHub Actions workflow YAML content.
func GenerateWorkflow(opts WorkflowOptions) string {
	labels := formatLabels(opts.RunnerLabels)

	pushTrigger := `  # push:
  #   branches: [main]`
	if opts.EnablePush {
		pushTrigger = `  push:
    branches: [main]`
	}

	prTrigger := `  # pull_request:
  #   branches: [main]`
	if opts.EnablePR {
		prTrigger = `  pull_request:
    branches: [main]`
	}

	return fmt.Sprintf(`# Generated by: ludus ci init
# This workflow runs the UE5 server pipeline on a self-hosted runner.
#
# Prerequisites:
#   - Self-hosted runner registered and running (ludus ci runner install --service)
#   - ludus.yaml present on the runner machine (gitignored; contains engine paths and AWS config)
#   - UE5 engine already built on the runner (skip-engine defaults to true)

name: Ludus UE5 Pipeline

on:
  workflow_dispatch:
    inputs:
      skip-engine:
        description: 'Skip engine build (use existing)'
        type: boolean
        default: true
      skip-game:
        description: 'Skip game server build'
        type: boolean
        default: false
      skip-container:
        description: 'Skip container build and push'
        type: boolean
        default: false
      skip-deploy:
        description: 'Skip deployment'
        type: boolean
        default: false
      dry-run:
        description: 'Dry run (print commands only)'
        type: boolean
        default: false
%s
%s

concurrency:
  group: ludus-pipeline
  cancel-in-progress: false

jobs:
  pipeline:
    name: UE5 Server Pipeline
    runs-on: %s
    timeout-minutes: 480

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build ludus
        run: go build -o ludus -v .

      - name: Validate prerequisites
        run: ./ludus init --verbose

      - name: Run pipeline
        run: |
          FLAGS=""
          if [ "${{ inputs.skip-engine }}" = "true" ]; then FLAGS="$FLAGS --skip-engine"; fi
          if [ "${{ inputs.skip-game }}" = "true" ]; then FLAGS="$FLAGS --skip-game"; fi
          if [ "${{ inputs.skip-container }}" = "true" ]; then FLAGS="$FLAGS --skip-container"; fi
          if [ "${{ inputs.skip-deploy }}" = "true" ]; then FLAGS="$FLAGS --skip-deploy"; fi
          if [ "${{ inputs.dry-run }}" = "true" ]; then FLAGS="$FLAGS --dry-run"; fi
          ./ludus run --verbose $FLAGS

      - name: Pipeline status
        if: always()
        run: ./ludus status
`, pushTrigger, prTrigger, labels)
}

// WriteWorkflow creates parent directories and writes the workflow file.
func WriteWorkflow(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing workflow file: %w", err)
	}
	return nil
}

// formatLabels formats runner labels as a YAML list: [self-hosted, linux, x64]
func formatLabels(labels []string) string {
	return "[" + strings.Join(labels, ", ") + "]"
}
