package wrapperconfig

import (
	"strings"
	"testing"
)

func TestYAML_Container(t *testing.T) {
	got := Config{
		GamePort:       7777,
		ExecutablePath: "./Lyra/Binaries/Linux/LyraServer",
		Args: []Arg{
			{Name: "Lyra"},
			PortArg("{{.ContainerPort}}"),
			{Name: "-log"},
		},
	}.YAML()

	want := `# Generated by ludus
log-config:
  wrapper-log-level: info

ports:
  gamePort: 7777

game-server-details:
  executable-file-path: "./Lyra/Binaries/Linux/LyraServer"
  game-server-args:
    - arg: "Lyra"
      pos: 0
    - arg: "-port="
      val: "{{.ContainerPort}}"
      pos: 1
    - arg: "-log"
      pos: 2
`
	if got != want {
		t.Errorf("container config mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestYAML_Anywhere(t *testing.T) {
	got := Config{
		Anywhere: &Anywhere{
			Profile:     "default",
			LocationARN: "arn:aws:gamelift:us-east-1::location/custom-ludus-dev",
			FleetARN:    "arn:aws:gamelift:us-east-1::fleet/fleet-123",
			IPv4:        "192.168.1.100",
		},
		GamePort:       7777,
		ExecutablePath: "C:/builds/PackagedServer/Lyra/Binaries/Win64/LyraServer.exe",
		Args: []Arg{
			{Name: "Lyra"},
			PortArg("7777"),
			{Name: "-log"},
		},
	}.YAML()

	want := `# Generated by ludus
log-config:
  wrapper-log-level: info

anywhere:
  provider: aws-profile
  profile: default
  location-arn: arn:aws:gamelift:us-east-1::location/custom-ludus-dev
  fleet-arn: arn:aws:gamelift:us-east-1::fleet/fleet-123
  ipv4: 192.168.1.100

ports:
  gamePort: 7777

game-server-details:
  executable-file-path: "C:/builds/PackagedServer/Lyra/Binaries/Win64/LyraServer.exe"
  game-server-args:
    - arg: "Lyra"
      pos: 0
    - arg: "-port="
      val: "7777"
      pos: 1
    - arg: "-log"
      pos: 2
`
	if got != want {
		t.Errorf("anywhere config mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestYAML_ManagedEC2(t *testing.T) {
	got := Config{
		LogLevel:       "debug",
		ServerLogsDir:  "./game-server-logs",
		GamePort:       5432,
		ExecutablePath: "Engine/Binaries/gamelift.ini",
		Args: []Arg{
			PortArg("{{.GamePort}}"),
			{Name: "-Map=Engine/Binaries/config.json"},
		},
	}.YAML()

	want := `# Generated by ludus
log-config:
  wrapper-log-level: debug
  game-server-logs-dir: ./game-server-logs

ports:
  gamePort: 5432

game-server-details:
  executable-file-path: "Engine/Binaries/gamelift.ini"
  game-server-args:
    - arg: "-port="
      val: "{{.GamePort}}"
      pos: 0
    - arg: "-Map=Engine/Binaries/config.json"
      pos: 1
`
	if got != want {
		t.Errorf("managed EC2 config mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// TestYAML_PortContractIsUniform pins the #550 contract across every target:
// the port argument must always be rendered with the '=' carried by the name,
// and a bare "-port" must never appear as an arg.
func TestYAML_PortContractIsUniform(t *testing.T) {
	variants := map[string]Config{
		"container": {Args: []Arg{PortArg("{{.ContainerPort}}")}},
		"anywhere":  {Args: []Arg{PortArg("7777")}},
		"ec2":       {Args: []Arg{PortArg("{{.GamePort}}")}},
	}

	for name, cfg := range variants {
		doc := cfg.YAML()
		if !strings.Contains(doc, `arg: "-port="`) {
			t.Errorf("%s: port arg missing '-port=':\n%s", name, doc)
		}
		for _, line := range strings.Split(doc, "\n") {
			if strings.Contains(line, `"arg: "-port""`) || strings.Contains(line, `- arg: "-port"`) {
				t.Errorf("%s: bare -port arg would be ignored by UE:\n%s", name, doc)
			}
		}
	}
}
