// Package wrapperconfig renders config.yaml documents for the Amazon GameLift
// Game Server Wrapper. Every ludus deploy target that launches the wrapper
// (container, Anywhere, managed EC2) builds a Config and renders it through
// YAML, so document structure and argument contracts live in one place.
package wrapperconfig

import (
	"fmt"
	"strconv"
	"strings"
)

// Arg is one entry in the generated game-server-args list.
type Arg struct {
	// Name is the literal first argv token. To pass a value to the UE server,
	// Name must carry its own '=' (e.g. "-port="): the wrapper appends Name
	// and Val as two separate argv entries (args.go: append(cmdArgs, name,
	// value)), and UE's parser matches the literal text "name=" — a bare
	// "-port 7777" is silently ignored by UE.
	Name string

	// Val is appended as the second argv token when non-empty. It may be a Go
	// text/template (e.g. "{{.GamePort}}"); the wrapper executes it at start
	// with the hosting event as data.
	Val string
}

// PortArg returns the game-port argument in the only form UE parses: a Name
// carrying the '=' plus the port value (literal or template).
func PortArg(val string) Arg {
	return Arg{Name: "-port=", Val: val}
}

// Anywhere holds the anywhere provider block; nil for non-Anywhere targets.
type Anywhere struct {
	Profile     string
	LocationARN string
	FleetARN    string
	IPv4        string
}

// Config is a complete wrapper config.yaml document.
type Config struct {
	// LogLevel is wrapper-log-level; defaults to "info" when empty.
	LogLevel string
	// ServerLogsDir optionally sets game-server-logs-dir under log-config.
	ServerLogsDir string
	// Anywhere is the anywhere provider block, or nil for other targets.
	Anywhere *Anywhere
	// GamePort is the static ports.gamePort value.
	GamePort int
	// ExecutablePath is the server binary path relative to the config file.
	ExecutablePath string
	// Args render as game-server-args; pos is assigned from list order.
	Args []Arg
}

// YAML renders the document. Sections appear in the wrapper's documented
// order; optional sections are omitted entirely so the wrapper's defaults apply.
func (c Config) YAML() string {
	var b strings.Builder
	b.WriteString("# Generated by ludus\n")

	fmt.Fprintf(&b, "log-config:\n  wrapper-log-level: %s\n", c.logLevel())
	if c.ServerLogsDir != "" {
		fmt.Fprintf(&b, "  game-server-logs-dir: %s\n", c.ServerLogsDir)
	}

	if a := c.Anywhere; a != nil {
		fmt.Fprintf(&b, "\nanywhere:\n  provider: aws-profile\n  profile: %s\n"+
			"  location-arn: %s\n  fleet-arn: %s\n  ipv4: %s\n",
			a.Profile, a.LocationARN, a.FleetARN, a.IPv4)
	}

	fmt.Fprintf(&b, "\nports:\n  gamePort: %d\n", c.GamePort)
	fmt.Fprintf(&b, "\ngame-server-details:\n  executable-file-path: %s\n",
		strconv.Quote(c.ExecutablePath))

	b.WriteString("  game-server-args:\n")
	for i, arg := range c.Args {
		fmt.Fprintf(&b, "    - arg: %s\n", strconv.Quote(arg.Name))
		if arg.Val != "" {
			fmt.Fprintf(&b, "      val: %s\n", strconv.Quote(arg.Val))
		}
		fmt.Fprintf(&b, "      pos: %d\n", i)
	}
	return b.String()
}

func (c Config) logLevel() string {
	if c.LogLevel == "" {
		return "info"
	}
	return c.LogLevel
}
